name: Build Pages

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Trigger Webhook
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "{
                  \"change\": \"${{
                    env.ALL_CHANGED_FILES }}\"
                }" \
            "${{ secrets.G_CHAT_WEBHOOK }}"